apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name | default .Release.Name }}-mysql
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.labelSelector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.label.app }}
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "{{ .Values.mysql.env.MYSQL_ROOT_PASSWORD }}"
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "{{ .Values.mysql.env.MYSQL_ALLOW_EMPTY_PASSWORD }}"
          - name: MYSQL_USER
            value: "{{ .Values.mysql.env.MYSQL_USER }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.mysql.env.MYSQL_PASSWORD }}"
          - name: MYSQL_DATABASE
            value: "{{ .Values.mysql.env.MYSQL_DATABASE }}"
        ports:
          - containerPort: 3306
