apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name | default .Release.Name }}-service
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.service.labelSelector | nindent 6 }}
